### ISSUE TITLE
Add p_median to math library

### ISSUE THREAD

**Issue by WesleyCeraso** [parallella/pal#57] opened 2015-06-02 21:15 UTC
This Issue tracks my contribution of p_median() to the math library.

**Comment by mateunho** [comment] 2015-06-03 21:18
Possible duplicate of #54 
> CC @olajep

**Comment by WesleyCeraso** [comment] 2015-06-03 21:22
Indeed, although there were no implementation of p_median when I started coding.
However the current implementation is O(n log n) because it sorts the whole array, and uses the stack instead of the heap (stack generally has little space available). My solution have a expected time of O(n) (uses QuickSelect) and uses heap.

**Comment by WesleyCeraso** [comment] 2015-06-05 15:38
While I was trying to perform tests between the current and mine implementations I realized the current is totally wrong and fixed it in the first commit 718a9ba.
After some improvements in my code it performed 5x faster than the current one for 1024x1024 arrays random filled, and it replaces the old implementation in the second commit cacf8f5.

**Comment by aolofsson** [comment] 2015-06-05 15:45
What is the purpose of the rand function in this context?

**Comment by WesleyCeraso** [comment] 2015-06-05 15:57
The same when used in quicksort, create an "expected running time". However for simplicity I removed the rand function. I had forgotten the srand call but already removed too.

**Comment by 6thimage** [comment] 2015-06-05 22:01
@WesleyCeraso thanks for pointing out that the wrong array was being used in the original implementation (the median_task example uses arrays that are sorted, and so was hiding the issue). Unfortunately, your fix in 718a9ba is incorrect, line 28 should not have a -1 in it.

Line 28 is executed when there is an odd number of elements, so only the division / bit shift is needed. For example, if n is 5, the bit shift reduces this to 2, which is the third (and middle) element of the array.

**Comment by WesleyCeraso** [comment] 2015-06-05 22:42
@6thimage Thanks for your comment. However, if you remeber that the c language is 0-based, you will realize that my implementation is correct.

**Comment by WesleyCeraso** [comment] 2015-06-05 22:50
@6thimage Thinking once more about it you are absolutely right, I`ll fix that asap.

**Comment by WesleyCeraso** [comment] 2015-06-05 23:23
@6thimage It`s fixed now. I`m going to run more test on my implementation, but I think it`s ok now. By the way, do you know what should we do when the input is zero length? Should we let it crash or what?

**Comment by 6thimage** [comment] 2015-06-05 23:55
@WesleyCeraso That is a good question - crashing is bad, as it will likely just hide the issue. Ideally, we need to report the error - unfortunately, the only output of the function is the returned array. Obviously, we can't set the returned value to zero to indicate an error, but perhaps it could be set to +/- inf or nan? Although this still has the effect of hiding the origin of the problem (if it returns nan, was the data nan before it entered the function?).

I think the best way to do this would be to have a global error variable for the math library, which we can set to a specific 'invalid input length' value to indicate an error, whilst returning nan from the function. This would then allow a program to check the cause of the nan. However, to keep all math functions similar, it would require that the majority of math functions update this error variable (of course only setting errors and not removing them). Which would be quite a large fundamental change to the workings of the math library, perhaps @aolofsson would like to weigh in on this.

**Comment by WesleyCeraso** [comment] 2015-06-06 00:38
@aolofsson My change is now quite smaller and faster than previous and is tested.
Regarding the conversation with @6thimage, couldn't we return 0/1 for no_error/error or something like that?

**Comment by 6thimage** [comment] 2015-06-06 00:55
@WesleyCeraso None of the other math functions return values, so for this function to return a value seems odd and against the rest of the library.

Thinking about it a bit more, I prefer the global variable approach as it would allow functions that don't care too much about their input to still be defined as void (saving operations and memory). For example, the mean function should have an output of zero for no input, and so it returning a constant no error value seems like a waste. Where as, the global variable approach allows functions to opt in for error reporting.

**Closed** 2015-06-07 19:30 UTC
